version: '2'
volumes:
 dbdata:

services:
 php:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
 mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - ./data:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=imagenet
    - MYSQL_USER=root
    - MYSQL_PASSWORD=secret
  ports:
    - "3306:3306"
  